site_name: BMDExpress-2
nav:
    - 'Home': 'index.md'
    - 'Overview of the Main View': 'overview-of-the-main-view.md'
    - 'How to Use the Application': 'how-to-use-the-application.md'
    - 'Statistical and Fold Change Prefiltering': 'statistical-and-fold-change-prefiltering.md'
    - 'Benchmark Dose Analysis': 'benchmark-dose-analysis.md'
    - 'Functional Classifications': 'functional-classifications.md'
    - 'Additional Information': 'additional-information.md'
    - 'Command Line': 'command-line.md'
theme: readthedocs