site_name: BMDExpress-2 Documentation
pages:
    - Home: index.md
    - Basic Workflow: basic_workflow.md
    - Main View: main_view.md
    - How To Use: how_to_use.md
    - Statistical and Fold Change Prefiltering: prefiltering.md
    - Benchmark Dose Analysis: bmd_analysis.md
    - Functional Classifications: functional_classifications.md
    - Additional Information: additional_information.md
    - Command Line Interface: command_line.md
theme: readthedocs